Repository engelsystem/engelsystem, pull requests merged in 2019-10, with the labels that each got.

#650 Shifts view: Persist hidden filters
  resources/assets/js/forms.js
  resources/views/pages/user-shifts.html
Labels: Type: Feature

#653 Return 403 forbidden on shifts json, atom export and ical export if api key is missing or invalid
  includes/controller/shifts_controller.php
  includes/helper/error_helper.php
  includes/includes.php
  includes/pages/user_atom.php
  includes/pages/user_ical.php
Labels: Priority: Low, Type: Bug(fix)

#655 CI: Build translation files for container and release archive, load .po if .mo not generated
  .gitignore
  README.md
  contrib/Dockerfile
  resources/lang/de_DE/default.mo
  resources/lang/en_US/default.mo
  resources/lang/pt_BR/default.mo
  src/Helpers/Translation/TranslationServiceProvider.php
  tests/Unit/Helpers/Translation/Assets/ba_RR/default.po
  tests/Unit/Helpers/Translation/TranslationServiceProviderTest.php
Labels: Type: Feature, Type: Refactor

#656 Frontend: Show language selects on every page
  resources/views/layouts/parts/navbar.twig
Labels: Type: Feature

#657 /credits: Make them translatable and use markdown
  resources/views/pages/credits.twig
Labels: Type: Feature

#662 Adds a docker dev setup
  .gitignore
  .gitlab-ci.yml
  README.md
  docker/.env
  docker/Dockerfile
  docker/dev/.env
  docker/dev/Dockerfile
  docker/dev/docker-compose.yml
  docker/docker-compose.yml
  docker/nginx/Dockerfile
  docker/nginx/nginx.conf
Labels: Status: In Progress, Type: Feature
