Repository engelsystem/engelsystem, pull requests merged in 2019-08, with the labels that each got.

#638 Fix CI
  contrib/nginx/Dockerfile
  package.json
Labels: Priority: High, Status: In Progress, Type: Bug(fix)

#639 Database: Use configured time zone
  src/Database/DatabaseServiceProvider.php
Labels: Priority: High, Type: Bug(fix)

#641 Shift signup/signout: Be more verbose
  includes/model/ShiftEntry_model.php
Labels: Type: Feature

#642 Metrics: Add database access time
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  src/Models/EventConfig.php
  tests/Unit/Controllers/Metrics/ControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Feature

#643 Shift page: show additional angeltypes if shift entries where found
  includes/view/Shifts_view.php
Labels: Type: Bug(fix)
