Repository engelsystem/engelsystem, pull requests merged in 2021-12, with the labels that each got.

#842 email option updated
  config/config.default.php
  db/factories/User/SettingsFactory.php
  db/migrations/2021_12_29_000000_users_settings_add_email_goody.php
  includes/pages/guest_login.php
  includes/pages/user_settings.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  resources/lang/pt_BR/default.po
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  src/Models/User/Settings.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Task, hacktoberfest-accepted

#866 Register page layout rework
  includes/pages/guest_login.php
Labels: Type: Refactor, PHP

#870 Replaced swift mailer with symfony mailer
  composer.json
  composer.lock
  config/config.default.php
  includes/controller/user_angeltypes_controller.php
  includes/helper/email_helper.php
  src/Events/Listener/News.php
  src/Mail/EngelsystemMailer.php
  src/Mail/Mailer.php
  src/Mail/MailerServiceProvider.php
  src/Mail/Transport/LogTransport.php
  src/Mail/Transport/Transport.php
  tests/Unit/Events/Listener/NewsTest.php
  tests/Unit/Mail/EngelsystemMailerTest.php
  tests/Unit/Mail/MailerServiceProviderTest.php
  tests/Unit/Mail/MailerTest.php
  tests/Unit/Mail/Transport/LogTransportTest.php
  tests/Unit/Mail/Transport/Stub/TransportImplementation.php
  tests/Unit/Mail/Transport/TransportTest.php
Labels: Type: Bug(fix), Type: Refactor
