Repository engelsystem/engelsystem, pull requests merged in 2022-10, with the labels that each got.

#966 Update twig
  composer.json
  composer.lock
Labels: hacktoberfest-accepted

#967 Fixed composer.lock hash
  composer.lock
Labels: hacktoberfest-accepted

#968 Change "delete" to "sign off" when removing user from shift
  includes/view/ShiftEntry_view.php
  resources/lang/de_DE/default.po
Labels: Type: Refactor, hacktoberfest-accepted

#964 Shift delete event
  config/app.php
  includes/controller/shifts_controller.php
  includes/helper/shift_helper.php
  includes/includes.php
  includes/mailer/shifts_mailer.php
  includes/model/Shifts_model.php
  includes/model/UserWorkLog_model.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  includes/pages/schedule/ImportSchedule.php
  resources/lang/de_DE/additional.po
  resources/lang/en_US/additional.po
  resources/views/emails/worklog-from-shift.twig
  src/Helpers/Shifts.php
  src/Mail/EngelsystemMailer.php
  tests/Unit/Helpers/ShiftsTest.php
Labels: Type: Feature, Type: Refactor

#969 Extend contributing guidelines
  CONTRIBUTING.md
Labels: Status: Needs discussion, hacktoberfest-accepted

#973 added dect option for rooms
  db/migrations/2022_10_17_000000_add_dect_to_rooms.php
  includes/model/Room_model.php
  includes/pages/admin_rooms.php
  includes/view/Rooms_view.php
  src/Models/Room.php
Labels: hacktoberfest-accepted

#971 add option to show mobile number of user in users view
  config/config.default.php
  db/factories/User/SettingsFactory.php
  db/migrations/2022_10_16_000000_add_mobile_show_to_users_settings.php
  includes/pages/guest_login.php
  includes/pages/user_settings.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  src/Models/Room.php
  src/Models/User/Settings.php
Labels: hacktoberfest-accepted

#975 Migrations: Removed references to models to prevent further migration issues
  db/migrations/2018_09_24_000000_create_event_config_table.php
  db/migrations/2018_10_01_000000_create_users_tables.php
  db/migrations/2018_12_27_000000_fix_missing_arrival_dates.php
  db/migrations/2020_09_02_000000_create_rooms_table.php
  db/migrations/2020_09_07_000000_create_worklogs_table.php
  db/migrations/2020_09_27_000000_add_timestamps_to_questions.php
  db/migrations/2020_11_20_000000_add_name_minutes_and_timestamps_to_schedules.php
  db/migrations/2021_05_23_000000_set_admin_password.php
  db/migrations/2021_12_29_000000_users_settings_add_email_goody.php
Labels: Type: Bug(fix), Type: Refactor

#978 add option to hide angeltype at registration
  db/migrations/2022_10_21_000000_add_hide_register_to_angeltypes.php
  includes/controller/angeltypes_controller.php
  includes/model/AngelType_model.php
  includes/pages/guest_login.php
  includes/view/AngelTypes_view.php
  resources/lang/de_DE/default.po
  tests/Unit/HasDatabase.php
Labels: Type: Feature, hacktoberfest-accepted

#977 Groups: Fix naming and update IDs
  db/migrations/2022_07_21_000000_fix_old_groups_table_id_and_name.php
  includes/pages/admin_groups.php
  includes/pages/admin_user.php
  includes/view/User_view.php
  src/Helpers/Authenticator.php
  src/Helpers/AuthenticatorServiceProvider.php
  tests/Unit/HasDatabase.php
  tests/Unit/Helpers/AuthenticatorServiceProviderTest.php
  tests/Unit/Helpers/AuthenticatorTest.php
Labels: Type: Refactor
