Repository engelsystem/engelsystem, pull requests merged in 2022-11, with the labels that each got.

#980 Permissions refactoring
  db/factories/GroupFactory.php
  db/factories/PrivilegeFactory.php
  db/migrations/2022_10_23_000000_create_privileges_and_groups_related_tables.php
  db/migrations/Reference.php
  includes/controller/users_controller.php
  includes/includes.php
  includes/model/UserAngelTypes_model.php
  includes/model/UserGroups_model.php
  includes/pages/admin_groups.php
  includes/pages/admin_user.php
  includes/pages/guest_login.php
  includes/sys_auth.php
  includes/view/User_view.php
  src/Helpers/Authenticator.php
  src/Helpers/AuthenticatorServiceProvider.php
  src/Models/Group.php
  src/Models/Privilege.php
  src/Models/User/User.php
  tests/Unit/Controllers/HomeControllerTest.php
  tests/Unit/Helpers/AuthenticatorServiceProviderTest.php
  tests/Unit/Helpers/AuthenticatorTest.php
  tests/Unit/Models/GroupTest.php
  tests/Unit/Models/PrivilegeTest.php
  tests/Unit/Models/User/UserTest.php
Labels: Type: Refactor, hacktoberfest-accepted

#987 Update frontend deps
  package.json
  resources/assets/themes/base.scss
  yarn.lock
Labels: Type: Bug(fix), Dependencies

#991 `<head>` optimizations
  resources/views/layouts/app.twig
  resources/views/layouts/maintenance.html
Labels: Type: Bug(fix)

#990 javascript improvements
  includes/pages/user_shifts.php
  includes/sys_form.php
  includes/view/PublicDashboard_view.php
  includes/view/UserDriverLicenses_view.php
  resources/assets/js/countdown.js
  resources/assets/js/forms.js
  resources/assets/js/sticky-headers.js
Labels: Type: Task

#994 Show driver's license button on user page when angeltype requires it
  includes/view/User_view.php
Labels: Type: Bug(fix)
