Repository engelsystem/engelsystem, pull requests merged in 2022-12, with the labels that each got.

#1013 fix select_array. needed for a correct format for select2
  includes/sys_page.php
Labels: Priority: High, Type: Bug(fix)

#1008 style input radios with bootstrap classes
  includes/sys_form.php
  resources/views/pages/design.twig
Labels: Type: Task

#1010 select2 width should be 100% to scale if the browser width changes
  resources/assets/js/forms.js
Labels: Type: Bug(fix)

#1021 fix tag nesting
  includes/view/User_view.php
Labels: Type: Bug(fix)

#997 Added AngelTypes model
  db/factories/AngelTypeFactory.php
  db/migrations/2022_11_08_000000_create_angel_types_table.php
  includes/controller/angeltypes_controller.php
  includes/controller/public_dashboard_controller.php
  includes/controller/rooms_controller.php
  includes/controller/shift_entries_controller.php
  includes/controller/shifts_controller.php
  includes/controller/user_angeltypes_controller.php
  includes/controller/users_controller.php
  includes/helper/oauth_helper.php
  includes/includes.php
  includes/model/AngelType_model.php
  includes/model/NeededAngelTypes_model.php
  includes/model/ShiftEntry_model.php
  includes/model/ShiftsFilter.php
  includes/model/Shifts_model.php
  includes/model/Stats.php
  includes/model/UserAngelTypes_model.php
  includes/model/User_model.php
  includes/pages/admin_free.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  includes/pages/guest_login.php
  includes/pages/schedule/ImportSchedule.php
  includes/pages/user_myshifts.php
  includes/pages/user_shifts.php
  includes/sys_template.php
  includes/view/AngelTypes_view.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/ShiftEntry_view.php
  includes/view/Shifts_view.php
  includes/view/UserAngelTypes_view.php
  includes/view/User_view.php
  src/Models/AngelType.php
  tests/Unit/Models/AngelTypeTest.php
Labels: Type: Refactor

#1014 use better icons
  includes/controller/angeltypes_controller.php
  includes/pages/admin_free.php
  includes/pages/admin_groups.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  includes/pages/user_shifts.php
  includes/sys_menu.php
  includes/view/AngelTypes_view.php
  includes/view/PublicDashboard_view.php
  includes/view/Rooms_view.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/ShiftTypes_view.php
  includes/view/Shifts_view.php
  includes/view/User_view.php
  resources/views/pages/faq/overview.twig
  resources/views/pages/news/overview.twig
  resources/views/pages/questions/overview.twig
Labels: Type: Task

#1023 Route parameter improvements
  config/routes.php
  includes/pages/schedule/ImportSchedule.php
  src/Controllers/Admin/FaqController.php
  src/Controllers/Admin/NewsController.php
  src/Controllers/Admin/QuestionsController.php
  src/Controllers/Admin/UserShirtController.php
  src/Controllers/Admin/UserWorkLogController.php
  src/Controllers/MessagesController.php
  src/Controllers/NewsController.php
  src/Controllers/OAuthController.php
  src/Controllers/PasswordResetController.php
  src/Middleware/RequestHandler.php
  src/Middleware/SessionHandler.php
  tests/Unit/Controllers/Admin/FaqControllerTest.php
  tests/Unit/Controllers/Admin/NewsControllerTest.php
  tests/Unit/Controllers/Admin/QuestionsControllerTest.php
  tests/Unit/Controllers/Admin/UserShirtControllerTest.php
  tests/Unit/Controllers/Admin/UserWorkLogControllerTest.php
  tests/Unit/Controllers/NewsControllerTest.php
Labels: Type: Refactor

#1035 set autocomplete attribute for password inputs
  includes/pages/admin_user.php
  includes/pages/guest_login.php
  includes/sys_form.php
  includes/view/User_view.php
  resources/views/macros/form.twig
  resources/views/pages/login.twig
  resources/views/pages/settings/password.twig
Labels: Type: Task

#1034 move js code for spinner into js file
  includes/sys_form.php
  resources/assets/js/forms.js
Labels: Type: Refactor

#1029 improve countdown logic
  includes/view/ShiftEntry_view.php
  includes/view/Shifts_view.php
  includes/view/User_view.php
  resources/assets/js/countdown.js
  resources/views/pages/design.twig
  resources/views/pages/login.twig
  src/Controllers/DesignController.php
Labels: Type: Refactor

#1044 Ignore the timezone configured in php.ini, better cleanup after feature tests
  config/config.default.php
  tests/Feature/ApplicationFeatureTest.php
Labels: Type: Bug(fix)

#1033 fix input radio id
  includes/pages/admin_shifts.php
  includes/sys_form.php
Labels: Type: Task

#1049 convert `switch` to `match`
  includes/controller/angeltypes_controller.php
  includes/controller/rooms_controller.php
  includes/controller/shift_entries_controller.php
  includes/controller/shifts_controller.php
  includes/controller/shifttypes_controller.php
  includes/controller/user_angeltypes_controller.php
  includes/controller/user_driver_licenses_controller.php
  includes/controller/users_controller.php
  includes/model/ShiftSignupState.php
  includes/view/ShiftCalendarShiftRenderer.php
  src/Controllers/Metrics/Stats.php
  src/Exceptions/Handlers/LegacyDevelopment.php
  src/Http/SessionServiceProvider.php
  src/Mail/MailerServiceProvider.php
  src/Models/EventConfig.php
  tests/Unit/Exceptions/Handlers/LegacyDevelopmentTest.php
Labels: Type: Refactor

#1052 Add prettier
  .editorconfig
  .gitlab-ci.yml
  .prettierrc.json
  CONTRIBUTING.md
  package.json
  resources/assets/js/dashboard.js
  resources/assets/js/date.js
  resources/assets/js/forms.js
  resources/assets/js/ready.js
  resources/assets/js/sticky-headers.js
  resources/assets/themes/barchart.scss
  resources/assets/themes/base.scss
  resources/assets/themes/card-glow.scss
  resources/assets/themes/cyborg_styles.scss
  resources/assets/themes/cyborg_variables.scss
  resources/assets/themes/dark.scss
  resources/assets/themes/error.scss
  resources/assets/themes/theme0.scss
  resources/assets/themes/theme1.scss
  resources/assets/themes/theme10.scss
  resources/assets/themes/theme11.scss
  resources/assets/themes/theme12.scss
  resources/assets/themes/theme13.scss
  resources/assets/themes/theme14.scss
  resources/assets/themes/theme15.scss
  resources/assets/themes/theme2.scss
  resources/assets/themes/theme3.scss
  resources/assets/themes/theme4.scss
  resources/assets/themes/theme5.scss
  resources/assets/themes/theme6.scss
  resources/assets/themes/theme7.scss
  resources/assets/themes/theme8.scss
  resources/assets/themes/theme9.scss
  yarn.lock
Labels: Type: Feature

#940 Config switches
  includes/controller/angeltypes_controller.php
  includes/view/AngelTypes_view.php
  includes/view/User_view.php
Labels: Type: Bug(fix)

#970 Make user view columns dynamic by config
  config/config.default.php
  includes/view/User_view.php
Labels: hacktoberfest-accepted

#1046 enable/disable all html-tags corresponding to a radio button checked state
  includes/pages/admin_shifts.php
  includes/sys_form.php
  resources/assets/js/forms.js
Labels: Type: Feature
