Repository engelsystem/engelsystem, pull requests merged in 2023-10, with the labels that each got.

#1226 rename rooms to locations
  includes/controller/shifts_controller.php
  includes/pages/admin_shifts.php
  includes/pages/schedule/ImportSchedule.php
  includes/pages/user_shifts.php
  includes/sys_menu.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/lang/pt_BR/default.po
  src/Controllers/Admin/RoomsController.php
  tests/Unit/Controllers/Admin/RoomsControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
  tests/Unit/Models/RoomTest.php
Labels: hacktoberfest-accepted

#1224 Fix form buttons in btn-group
  resources/assets/themes/base.scss
Labels: Type: Bug(fix), hacktoberfest-accepted

#1225 Shifts: Fix sign up text when self sign up is disallowed
  includes/view/ShiftCalendarShiftRenderer.php
Labels: Type: Bug(fix), hacktoberfest-accepted

#1227 Handle email send errors in Mailer class
  includes/controller/user_angeltypes_controller.php
  includes/helper/email_helper.php
  includes/helper/shift_helper.php
  src/Events/Listener/Messages.php
  src/Events/Listener/News.php
  src/Mail/EngelsystemMailer.php
  src/Mail/Mailer.php
  tests/Unit/Events/Listener/MessagesTest.php
  tests/Unit/Events/Listener/NewsTest.php
  tests/Unit/Mail/EngelsystemMailerTest.php
  tests/Unit/Mail/MailerTest.php
Labels: Type: Refactor, hacktoberfest-accepted

#1228 cleaning translations
  includes/controller/angeltypes_controller.php
  includes/controller/event_config_controller.php
  includes/controller/shifts_controller.php
  includes/pages/admin_free.php
  includes/pages/admin_groups.php
  includes/pages/admin_shifts.php
  includes/pages/admin_user.php
  includes/pages/user_shifts.php
  includes/sys_menu.php
  includes/view/AngelTypes_view.php
  includes/view/EventConfig_view.php
  includes/view/ShiftEntry_view.php
  includes/view/ShiftTypes_view.php
  includes/view/Shifts_view.php
  includes/view/UserDriverLicenses_view.php
  includes/view/User_view.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/admin/schedule/load.twig
  resources/views/pages/login.twig
  resources/views/pages/password/reset-form.twig
  resources/views/pages/password/reset.twig
  src/Controllers/SettingsController.php
Labels: hacktoberfest-accepted

#1232 removing pt translation
  resources/lang/pt_BR/default.po
Labels: Type: Task

#1223 Updated email_goody opt in text
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
Labels: Type: Refactor, hacktoberfest-accepted
