Repository engelsystem/engelsystem, pull requests merged in 2023-02, with the labels that each got.

#1037 Improve migration
  db/migrations/2018_01_01_000003_fix_old_tables.php
  db/migrations/2018_01_01_000005_add_angel_supporter_permissions.php
  db/migrations/2018_09_24_000000_create_event_config_table.php
  db/migrations/2018_12_21_000000_change_users_contact_dect_field_size.php
  db/migrations/2018_12_27_000000_fix_missing_arrival_dates.php
  db/migrations/2019_09_07_000001_create_schedule_shift_table.php
  db/migrations/2019_10_15_000000_create_news_table.php
  db/migrations/2019_11_25_000000_create_messages_table.php
  db/migrations/2019_11_29_000000_create_questions_table.php
  db/migrations/2019_12_03_000000_user_personal_data_add_pronoun_field.php
  db/migrations/2020_04_07_000000_change_mysql_database_encoding_to_utf8mb4.php
  db/migrations/2020_11_20_000000_add_name_minutes_and_timestamps_to_schedules.php
  db/migrations/2020_12_25_000000_add_email_news_to_users_settings.php
  db/migrations/2020_12_25_000000_oauth_add_tokens.php
  db/migrations/2020_12_26_000000_news_add_is_pinned.php
  db/migrations/2020_12_28_000001_oauth_change_tokens_to_text.php
  db/migrations/2021_10_12_000000_add_shifts_description.php
  db/migrations/2021_12_29_000000_users_settings_add_email_goody.php
  db/migrations/2022_07_21_000000_fix_old_groups_table_id_and_name.php
  db/migrations/2022_10_16_000000_add_mobile_show_to_users_settings.php
  db/migrations/2022_10_17_000000_add_dect_to_rooms.php
  db/migrations/2022_10_21_000000_add_hide_register_to_angeltypes.php
  db/migrations/2022_10_23_000000_create_privileges_and_groups_related_tables.php
  db/migrations/2022_11_06_000000_shifttype_remove_angeltype.php
Labels: Type: Task

#1086 Unified user notifications
  includes/controller/angeltypes_controller.php
  includes/controller/shift_entries_controller.php
  includes/controller/user_angeltypes_controller.php
  includes/helper/email_helper.php
  includes/helper/message_helper.php
  includes/pages/admin_shifts.php
  includes/pages/guest_login.php
  includes/pages/schedule/ImportSchedule.php
  includes/view/ShiftEntry_view.php
  includes/view/UserAngelTypes_view.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  resources/lang/pt_BR/default.po
  resources/views/layouts/parts/messages.twig
  resources/views/pages/login.twig
  src/Controllers/Admin/FaqController.php
  src/Controllers/Admin/NewsController.php
  src/Controllers/Admin/QuestionsController.php
  src/Controllers/Admin/UserShirtController.php
  src/Controllers/Admin/UserWorkLogController.php
  src/Controllers/AuthController.php
  src/Controllers/FaqController.php
  src/Controllers/HasUserNotifications.php
  src/Controllers/NewsController.php
  src/Controllers/NotificationType.php
  src/Controllers/PasswordResetController.php
  src/Controllers/QuestionsController.php
  src/Controllers/SettingsController.php
  src/Middleware/ErrorHandler.php
  src/Renderer/Twig/Extensions/Legacy.php
  src/Renderer/Twig/Extensions/Notification.php
  src/Renderer/TwigServiceProvider.php
  tests/Unit/Controllers/Admin/FaqControllerTest.php
  tests/Unit/Controllers/Admin/NewsControllerTest.php
  tests/Unit/Controllers/AuthControllerTest.php
  tests/Unit/Controllers/ControllerTest.php
  tests/Unit/Controllers/HasUserNotificationsTest.php
  tests/Unit/Controllers/PasswordResetControllerTest.php
  tests/Unit/Controllers/SettingsControllerTest.php
  tests/Unit/Controllers/Stub/HasUserNotificationsImplementation.php
  tests/Unit/Middleware/ErrorHandlerTest.php
  tests/Unit/Renderer/Twig/Extensions/LegacyTest.php
  tests/Unit/Renderer/Twig/Extensions/NotificationTest.php
Labels: Type: Refactor

#1097 Reimplemented about angeltypes page
  config/routes.php
  includes/controller/angeltypes_controller.php
  includes/pages/guest_login.php
  includes/pages/user_shifts.php
  includes/view/AngelTypes_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/angeltypes/about.twig
  resources/views/pages/login.twig
  src/Controllers/AngelTypesController.php
  tests/Unit/Controllers/AngelTypesControllerTest.php
Labels: Type: Refactor

#1088 Translate more date / time outputs
  includes/controller/angeltypes_controller.php
  includes/controller/rooms_controller.php
  includes/controller/shifts_controller.php
  includes/helper/shift_helper.php
  includes/mailer/shifts_mailer.php
  includes/pages/admin_arrive.php
  includes/pages/admin_shifts.php
  includes/pages/admin_user.php
  includes/pages/user_myshifts.php
  includes/pages/user_shifts.php
  includes/view/ShiftEntry_view.php
  includes/view/ShiftsFilterRenderer.php
  includes/view/Shifts_view.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  src/Controllers/DesignController.php
Labels: Type: Bug(fix), Type: Refactor

#1101 Reimplemented admin room pages
  config/routes.php
  includes/controller/angeltypes_controller.php
  includes/controller/public_dashboard_controller.php
  includes/controller/rooms_controller.php
  includes/controller/shifts_controller.php
  includes/includes.php
  includes/model/Room_model.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  includes/pages/user_shifts.php
  includes/sys_menu.php
  includes/view/Rooms_view.php
  resources/assets/js/forms.js
  resources/assets/themes/base.scss
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/admin/rooms/edit.twig
  resources/views/admin/rooms/index.twig
  resources/views/macros/base.twig
  resources/views/macros/form.twig
  resources/views/pages/design.twig
  src/Controllers/Admin/RoomsController.php
  src/Http/Response.php
  src/Http/Validation/Validator.php
  src/Middleware/LegacyMiddleware.php
  src/Renderer/Twig/Extensions/Session.php
  tests/Unit/Controllers/Admin/RoomsControllerTest.php
  tests/Unit/Http/ResponseTest.php
  tests/Unit/Http/Validation/ValidatorTest.php
  tests/Unit/Middleware/ErrorHandlerTest.php
  tests/Unit/Renderer/Twig/Extensions/SessionTest.php
Labels: Type: Refactor

#1102 Added email notification on new private messages
  config/app.php
  db/factories/User/SettingsFactory.php
  db/migrations/2023_02_26_000000_AddEmailMessagesToUsersSettings.php
  includes/pages/guest_login.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/emails/messages-new.twig
  resources/views/pages/settings/profile.twig
  src/Controllers/MessagesController.php
  src/Controllers/SettingsController.php
  src/Events/Listener/Messages.php
  src/Models/User/Settings.php
  tests/Unit/Controllers/MessagesControllerTest.php
  tests/Unit/Controllers/SettingsControllerTest.php
  tests/Unit/Events/Listener/MessagesTest.php
Labels: Type: Feature

#1103 Use git HEAD for version parsing
  src/Helpers/Version.php
  src/Helpers/VersionServiceProvider.php
  tests/Unit/Helpers/Stub/files/logs/HEAD
  tests/Unit/Helpers/VersionServiceProviderTest.php
  tests/Unit/Helpers/VersionTest.php
Labels: Type: Feature
