Repository engelsystem/engelsystem, pull requests merged in 2023-01, with the labels that each got.

#1027 Shifts filter
  includes/pages/user_shifts.php
  includes/sys_template.php
  resources/assets/js/forms.js
  resources/assets/themes/base.scss
  resources/views/pages/user-shifts.html
Labels: Type: Refactor

#1065 Refactored UUID generation: use pseudo unique named UUID for schedules
  includes/pages/admin_shifts.php
  includes/pages/schedule/ImportSchedule.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  src/Helpers/Uuid.php
  src/Helpers/UuidServiceProvider.php
  tests/Unit/Helpers/UuidServiceProviderTest.php
  tests/Unit/Helpers/UuidTest.php
Labels: Type: Feature

#1053 Replace select 2 with choices.js and kill jQuery
  package.json
  resources/assets/js/forms.js
  resources/assets/js/vendor.js
  resources/assets/themes/base.scss
  resources/assets/themes/choices.scss
  resources/assets/themes/dark.scss
  resources/views/pages/design.twig
  src/Controllers/DesignController.php
  yarn.lock
Labels: Type: Refactor

#948 Custom translations
  .gitignore
  src/Helpers/Translation/TranslationServiceProvider.php
  tests/Unit/Helpers/Translation/Assets/ba_RR/additional.po
  tests/Unit/Helpers/Translation/Assets/ba_RR/default.po
  tests/Unit/Helpers/Translation/Assets/config/lang/ba_RR/custom.po
  tests/Unit/Helpers/Translation/TranslationServiceProviderTest.php
Labels: Type: Feature

#1066 ShiftEntry
  db/factories/Shifts/ShiftEntryFactory.php
  db/migrations/2022_12_30_000000_create_shift_entries_table.php
  includes/controller/public_dashboard_controller.php
  includes/controller/shift_entries_controller.php
  includes/controller/shifts_controller.php
  includes/controller/users_controller.php
  includes/mailer/shifts_mailer.php
  includes/model/NeededAngelTypes_model.php
  includes/model/ShiftEntry_model.php
  includes/model/Shifts_model.php
  includes/model/Stats.php
  includes/model/User_model.php
  includes/pages/admin_active.php
  includes/pages/admin_free.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  includes/pages/schedule/ImportSchedule.php
  includes/pages/user_ical.php
  includes/pages/user_myshifts.php
  includes/pages/user_shifts.php
  includes/view/ShiftCalendarRenderer.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/ShiftEntry_view.php
  includes/view/Shifts_view.php
  includes/view/User_view.php
  src/Controllers/Metrics/Stats.php
  src/Models/AngelType.php
  src/Models/Shifts/Shift.php
  src/Models/Shifts/ShiftEntry.php
  src/Models/User/User.php
  src/Renderer/TwigServiceProvider.php
  tests/Unit/Controllers/Metrics/StatsTest.php
  tests/Unit/FactoriesTest.php
  tests/Unit/Models/AngelTypeTest.php
  tests/Unit/Models/Shifts/ShiftEntryTest.php
  tests/Unit/Models/Shifts/ShiftTest.php
  tests/Unit/Models/User/UserTest.php
  tests/Unit/Renderer/Twig/Extensions/ExtensionTest.php
  tests/Unit/Renderer/TwigServiceProviderTest.php
Labels: Type: Refactor

#1069 NeededAngelTypes
  db/factories/Shifts/NeededAngelTypeFactory.php
  db/migrations/2023_01_17_000000_create_needed_angel_types_table.php
  includes/controller/shifts_controller.php
  includes/model/NeededAngelTypes_model.php
  includes/model/Shifts_model.php
  includes/model/Stats.php
  includes/pages/admin_rooms.php
  includes/pages/admin_shifts.php
  src/Models/AngelType.php
  src/Models/Room.php
  src/Models/Shifts/NeededAngelType.php
  src/Models/Shifts/Shift.php
  tests/Unit/Models/AngelTypeTest.php
  tests/Unit/Models/RoomTest.php
  tests/Unit/Models/Shifts/NeededAngelTypeTest.php
  tests/Unit/Models/Shifts/ShiftTest.php
Labels: Type: Refactor

#1083 change port for local development to 5080
  DEVELOPMENT.md
  docker/dev/docker-compose.yml
  docker/docker-compose.yml
Labels: Type: Bug(fix), Status: Needs discussion
