Repository engelsystem/engelsystem, pull requests merged in 2023-11, with the labels that each got.

#1243 rename shirt size keys G to F
  config/config.default.php
  db/migrations/2023_10_25_000000_degender_shirt_sizes.php
Labels: hacktoberfest-accepted

#1242 Add back buttons on edit and deletion pages
  includes/controller/shifts_controller.php
  includes/pages/admin_shifts.php
  includes/pages/admin_user.php
  includes/view/AngelTypes_view.php
  includes/view/ShiftEntry_view.php
  includes/view/ShiftTypes_view.php
  includes/view/UserDriverLicenses_view.php
  includes/view/User_view.php
  resources/views/admin/rooms/index.twig
  resources/views/admin/user/edit-shirt.twig
  resources/views/admin/user/edit-worklog.twig
  resources/views/pages/faq/edit.twig
  resources/views/pages/news/edit.twig
  resources/views/pages/questions/edit.twig
  resources/views/pages/sign-up.twig
Labels: hacktoberfest-accepted

#1237 Allow the creation of new entity's from overview pages (+ sign)
  includes/pages/user_shifts.php
  includes/view/AngelTypes_view.php
  includes/view/ShiftTypes_view.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  resources/views/pages/user-shifts.html
Labels: hacktoberfest-accepted

#1221 make required fields configurable
  config/config.default.php
  includes/view/User_view.php
  resources/lang/de_DE/additional.po
  resources/lang/en_US/additional.po
  resources/views/pages/settings/profile.twig
  resources/views/pages/sign-up.twig
  src/Controllers/SettingsController.php
  src/Controllers/SignUpController.php
  src/Factories/User.php
  tests/Unit/Controllers/SettingsControllerTest.php
  tests/Utils/SignUpConfig.php
Labels: Type: Feature, hacktoberfest-accepted

#1233 Shifts feed: Added URL to shit and shifttype name & description
  src/Controllers/FeedController.php
  tests/Unit/Controllers/FeedControllerTest.php
Labels: Type: Feature

#1231 Rename rooms to locations
  config/routes.php
  db/factories/LocationFactory.php
  db/factories/Shifts/NeededAngelTypeFactory.php
  db/factories/Shifts/ShiftFactory.php
  db/migrations/2023_10_13_000000_rename_rooms_to_locations.php
  includes/controller/angeltypes_controller.php
  includes/controller/locations_controller.php
  includes/controller/public_dashboard_controller.php
  includes/controller/shift_entries_controller.php
  includes/controller/shifts_controller.php
  includes/helper/shift_helper.php
  includes/includes.php
  includes/mailer/shifts_mailer.php
  includes/model/NeededAngelTypes_model.php
  includes/model/ShiftEntry_model.php
  includes/model/ShiftsFilter.php
  includes/model/Shifts_model.php
  includes/model/Stats.php
  includes/pages/admin_shifts.php
  includes/pages/schedule/ImportSchedule.php
  includes/pages/user_myshifts.php
  includes/pages/user_shifts.php
  includes/sys_menu.php
  includes/view/Locations_view.php
  includes/view/PublicDashboard_view.php
  includes/view/ShiftCalendarRenderer.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/ShiftEntry_view.php
  includes/view/Shifts_view.php
  includes/view/User_view.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/lang/pt_BR/default.po
  resources/views/admin/locations/edit.twig
  resources/views/admin/locations/index.twig
  resources/views/admin/schedule/load.twig
  resources/views/api/ical.twig
  resources/views/emails/worklog-from-shift.twig
  resources/views/pages/user-shifts.html
  src/Controllers/Admin/LocationsController.php
  src/Controllers/FeedController.php
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  src/Middleware/LegacyMiddleware.php
  src/Models/Location.php
  src/Models/Shifts/NeededAngelType.php
  src/Models/Shifts/Shift.php
  tests/Unit/Controllers/Admin/LocationsControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
  tests/Unit/FactoriesTest.php
  tests/Unit/Models/LocationTest.php
  tests/Unit/Models/RoomTest.php
  tests/Unit/Models/Shifts/NeededAngelTypeTest.php
  tests/Unit/Models/Shifts/ShiftTest.php
Labels: Type: Refactor, PHP

#1239 Recreated shifts history page
  config/routes.php
  includes/pages/admin_arrive.php
  includes/pages/admin_shifts.php
  includes/view/ShiftEntry_view.php
  includes/view/Shifts_view.php
  includes/view/UserAngelTypes_view.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/admin/shifts/history.twig
  resources/views/admin/user/edit-worklog.twig
  src/Controllers/Admin/ShiftsController.php
  src/Middleware/LegacyMiddleware.php
  tests/Unit/Controllers/Admin/ShiftsControllerTest.php
Labels: Type: Refactor, PHP

#1240 Recreated shift type admin backend
  config/routes.php
  includes/controller/shifttypes_controller.php
  includes/includes.php
  includes/pages/admin_shifts.php
  includes/sys_menu.php
  includes/view/ShiftTypes_view.php
  includes/view/Shifts_view.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/admin/shifttypes/edit.twig
  resources/views/admin/shifttypes/index.twig
  resources/views/admin/shifttypes/view.twig
  src/Controllers/Admin/ShiftTypesController.php
  src/Middleware/LegacyMiddleware.php
  tests/Unit/Controllers/Admin/ShiftTypeControllerTest.php
Labels: Type: Refactor, PHP
