Repository engelsystem/engelsystem, pull requests merged in 2023-09, with the labels that each got.

#1212 Schedule import: Show error message on schedule parsing errors
  src/Helpers/Schedule/XmlParser.php
  tests/Unit/Helpers/Schedule/Assets/schedule-invalid.html
  tests/Unit/Helpers/Schedule/XmlParserTest.php
Labels: Type: Bug(fix)

#1214 Add event name and day of event to mail footer
  resources/views/emails/mail.twig
Labels: Type: Feature

#1155 Allow admins to remove entries from some config arrays
  README.md
  config/config.default.php
  src/Config/ConfigServiceProvider.php
  tests/Unit/Config/ConfigServiceProviderTest.php
Labels: Type: Refactor

#1215 rename is_important to is_highlighted
  db/factories/NewsFactory.php
  db/migrations/2023_09_18_000000_news_rename_important_to_highlight.php
  includes/controller/public_dashboard_controller.php
  includes/view/PublicDashboard_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/news/edit.twig
  resources/views/pages/news/overview.twig
  src/Controllers/Admin/NewsController.php
  src/Controllers/NewsController.php
  src/Models/News.php
  tests/Unit/Controllers/Admin/NewsControllerTest.php
  tests/Unit/Controllers/NewsControllerTest.php
Labels: Type: Refactor

#1195 add hide angeltype in shift view option for angeltypes
  db/factories/AngelTypeFactory.php
  db/migrations/2023_08_27_000000_add_hide_on_shift_view_to_angeltypes.php
  includes/controller/angeltypes_controller.php
  includes/pages/user_shifts.php
  includes/view/AngelTypes_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  src/Models/AngelType.php
Labels: Type: Feature
