Repository engelsystem/engelsystem, pull requests merged in 2023-12, with the labels that each got.

#1272 Implement schedule deletion
  includes/pages/schedule/ImportSchedule.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/admin/schedule/edit.twig
  resources/views/admin/schedule/index.twig
  resources/views/macros/form.twig
Labels: Type: Feature

#1281 highlight freeloaded shifts in user myshifts view
  includes/view/User_view.php
Labels: Type: Feature

#1286 edit user nick needs buerocrat
  db/migrations/2023_12_21_000000_add_user_edit_permission.php
  includes/pages/admin_user.php
Labels: Type: Feature

#1269 Added user id to logs
  db/migrations/2023_12_06_000000_add_user_id_to_log_entries.php
  db/migrations/2023_12_06_000001_add_logs_all_permission.php
  db/migrations/Reference.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/admin/log.twig
  src/Controllers/Admin/LogsController.php
  src/Logger/Logger.php
  src/Logger/UserAwareLogger.php
  src/Models/LogEntry.php
  tests/Unit/Controllers/Admin/LogsControllerTest.php
  tests/Unit/Logger/LoggerTest.php
  tests/Unit/Logger/UserAwareLoggerTest.php
  tests/Unit/Models/LogEntryTest.php
Labels: Type: Feature, PHP

#1280 Implement random shift button
  config/routes.php
  includes/pages/user_shifts.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/pages/user-shifts.html
  src/Controllers/ShiftsController.php
  tests/Unit/Controllers/ShiftsControllerTest.php
Labels: Type: Feature

#1289 Show "not marked as arrived" Notification only from set arrival date
  includes/pages/user_shifts.php
  includes/sys_menu.php
  includes/view/Locations_view.php
  includes/view/User_view.php
Labels: Type: Refactor

#1293 Header/Footer items config: Add configurable permissions
  config/config.default.php
  resources/views/layouts/parts/footer.twig
  resources/views/layouts/parts/navbar.twig
Labels: Type: Feature

#1287 Send notifications on news updates
  config/app.php
  resources/lang/de_DE/additional.po
  resources/lang/de_DE/default.po
  resources/lang/en_US/additional.po
  resources/lang/en_US/default.po
  resources/views/emails/news-updated.twig
  resources/views/pages/news/edit.twig
  src/Controllers/Admin/NewsController.php
  src/Events/Listener/News.php
  tests/Unit/Controllers/Admin/NewsControllerTest.php
  tests/Unit/Events/Listener/NewsTest.php
Labels: Type: Feature

#1299 Shifts creation: Add reset to previous input
  includes/pages/admin_shifts.php
  includes/sys_form.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
Labels: Type: Feature

#1291 Update composer packages
  composer.json
  composer.lock
Labels: Dependencies, PHP

#1310 random shift: check for schedule load flag
  src/Controllers/ShiftsController.php
Labels: Priority: High, Type: Bug(fix)

#1311 Fix error messages
  includes/controller/shift_entries_controller.php
  includes/pages/admin_user.php
Labels: Type: Bug(fix)

#1314 not arrived users metrics
  includes/pages/admin_user.php
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  tests/Unit/Controllers/Metrics/ControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Feature

#1313 37c3 Theme
  config/config.default.php
  resources/assets/themes/theme17.scss
  resources/assets/themes/theme17/GabriellaHeavy.otf
  resources/assets/themes/theme17/VCROCDFaux.ttf
  resources/assets/themes/theme17/VCROCDFaux.woff
  resources/assets/themes/theme17/VCROCDFaux.woff2
Labels: Priority: High, Type: Feature

#1315 add user info to metrics
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Feature

#1324 add shifttypes and angeltypes count to metrics
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Feature
