Repository engelsystem/engelsystem, pull requests merged in 2024-08, with the labels that each got.

#1404 max length to some input fields
  includes/controller/angeltypes_controller.php
  includes/pages/admin_shifts.php
  includes/view/AngelTypes_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/admin/locations/edit.twig
  resources/views/admin/schedule/edit.twig
  resources/views/admin/shifttypes/edit.twig
  resources/views/pages/faq/edit.twig
  resources/views/pages/news/edit.twig
  src/Controllers/Admin/FaqController.php
  src/Controllers/Admin/LocationsController.php
  src/Controllers/Admin/NewsController.php
  src/Controllers/Admin/ScheduleController.php
  src/Controllers/Admin/ShiftTypesController.php
Labels: Type: Bug(fix)

#1398 Worklog
  config/config.default.php
  config/routes.php
  includes/view/User_view.php
  src/Controllers/Admin/UserWorklogController.php
  src/Events/Listener/Shifts.php
  tests/Unit/Controllers/Admin/UserWorklogControllerTest.php
Labels: Type: Bug(fix), Type: Feature

#1419 Prefetch data
  includes/pages/admin_active.php
  includes/pages/admin_free.php
  resources/views/admin/locations/index.twig
  resources/views/admin/log.twig
  resources/views/admin/schedule/index.twig
  resources/views/pages/news/index.twig
  src/Controllers/Admin/LocationsController.php
  src/Controllers/Admin/ScheduleController.php
Labels: Type: Task

#1416 Fix user-shifts bug
  includes/model/Shifts_model.php
  includes/view/ShiftCalendarRenderer.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/Shifts_view.php
Labels: Type: Bug(fix)

#1367 Add support for file-based docker secrets
  config/config.default.php
  src/helpers.php
  tests/Unit/Assets/foo_secret
  tests/Unit/HelpersTest.php
Labels: Type: Feature, Status: Needs discussion
