Repository engelsystem/engelsystem, pull requests merged in 2024-11, with the labels that each got.

#1442 simplify e-mail preferences on registration
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/registration.twig
  src/Factories/User.php
  tests/Unit/Factories/UserTest.php
Labels: Type: Feature, hacktoberfest-accepted

#1443 Show some shifts for users without angeltype
  includes/pages/user_shifts.php
Labels: hacktoberfest-accepted

#1453 38c3 Design
  config/config.default.php
  resources/assets/themes/theme18.scss
  resources/assets/themes/theme18/Pilowlava-License.txt
  resources/assets/themes/theme18/Pilowlava-Regular.woff2
  resources/assets/themes/theme18/SpaceGrotesk-License.txt
  resources/assets/themes/theme18/SpaceGrotesk-Regular.woff2
  resources/assets/themes/theme18/blob-collision-wall-1.svg
Labels: Type: Feature
