Repository engelsystem/engelsystem, pull requests merged in 2024-03, with the labels that each got.

#1362 IfSG improvements
  config/routes.php
  db/factories/User/LicenseFactory.php
  db/migrations/2024_03_05_000000_add_ifsg_confirmed_to_users_licenses.php
  db/migrations/2024_03_05_000001_add_user_ifsg_edit_permission.php
  includes/controller/users_controller.php
  includes/view/AngelTypes_view.php
  includes/view/UserAngelTypes_view.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/settings/certificates-admin.twig
  resources/views/pages/settings/certificates.twig
  resources/views/pages/settings/settings.twig
  src/Controllers/Admin/UserSettingsController.php
  src/Controllers/SettingsController.php
  src/Models/AngelType.php
  src/Models/User/License.php
  tests/Unit/Controllers/Admin/UserSettingsControllerTest.php
  tests/Unit/Controllers/SettingsControllerTest.php
Labels: Type: Feature

#1359 fix table on admin_active for length and score
  includes/pages/admin_active.php
Labels: Type: Bug(fix)

#1294 Shift deletion: Simplify notification flow
  config/app.php
  includes/controller/shifts_controller.php
  includes/helper/shift_helper.php
  resources/views/emails/worklog-from-shift.twig
  src/Controllers/Admin/LocationsController.php
  src/Controllers/Admin/ScheduleController.php
  src/Controllers/Admin/ShiftTypesController.php
  src/Controllers/Admin/ShiftsController.php
  tests/Unit/Controllers/Admin/LocationsControllerTest.php
  tests/Unit/Controllers/Admin/ScheduleControllerTest.php
  tests/Unit/Controllers/Admin/ShiftTypesControllerTest.php
  tests/Unit/Controllers/Admin/ShiftsControllerTest.php
Labels: Type: Refactor

#1366 driving license improvements
  config/config.default.php
  config/routes.php
  db/factories/User/LicenseFactory.php
  db/migrations/2024_03_13_000000_add_drive_confirmed_to_users_licenses.php
  db/migrations/2024_03_13_000001_add_user_drive_edit_permission.php
  includes/controller/angeltypes_controller.php
  includes/controller/users_controller.php
  includes/view/AngelTypes_view.php
  includes/view/User_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/settings/certificates-admin.twig
  resources/views/pages/settings/certificates.twig
  src/Controllers/Admin/UserSettingsController.php
  src/Controllers/SettingsController.php
  src/Models/User/License.php
  tests/Unit/Controllers/Admin/UserSettingsControllerTest.php
  tests/Unit/Controllers/SettingsControllerTest.php
Labels: Type: Feature
