Repository engelsystem/engelsystem, pull requests merged in 2024-04, with the labels that each got.

#1374 add 'enable_email_goody' config and fix wording
  config/config.default.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/registration.twig
  resources/views/pages/settings/profile.twig
  src/Controllers/RegistrationController.php
  src/Controllers/SettingsController.php
  tests/Unit/Controllers/SettingsControllerTest.php
Labels: Type: Feature

#1166 Add registration link when password is disabled (when using OAuth)
  config/config.default.php
  resources/assets/js/forms.js
  resources/views/layouts/parts/navbar.twig
  resources/views/pages/angeltypes/about.twig
  resources/views/pages/login.twig
Labels: Type: Feature

#1385 rename goody into goodie
  config/config.default.php
  db/factories/User/SettingsFactory.php
  db/migrations/2024_04_10_000000_rename_goody_to_goodie.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/pages/registration.twig
  resources/views/pages/settings/profile.twig
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  src/Controllers/RegistrationController.php
  src/Controllers/SettingsController.php
  src/Factories/User.php
  src/Models/User/Settings.php
  tests/Feature/Controllers/RegistrationControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
  tests/Unit/Controllers/SettingsControllerTest.php
Labels: Type: Bug(fix), Type: Refactor

#1386 Shirt to goodie
  config/routes.php
  db/factories/User/StateFactory.php
  db/migrations/2024_04_10_000001_rename_shirt_to_goodie.php
  includes/controller/users_controller.php
  includes/model/User_model.php
  includes/pages/admin_active.php
  includes/pages/admin_user.php
  includes/sys_menu.php
  includes/view/User_view.php
  resources/lang/en_US/default.po
  resources/views/admin/user/edit-goodie.twig
  resources/views/pages/settings/profile.twig
  src/Controllers/Admin/UserGoodieController.php
  src/Controllers/Metrics/Controller.php
  src/Controllers/Metrics/Stats.php
  src/Controllers/SettingsController.php
  src/Models/User/State.php
  tests/Unit/Controllers/Admin/UserGoodieControllerTest.php
  tests/Unit/Controllers/Metrics/ControllerTest.php
  tests/Unit/Controllers/Metrics/StatsTest.php
Labels: Type: Refactor

#1391 docker dev setup on localhost
  docker/dev/docker-compose.yml
Labels: Type: Task
