Repository engelsystem/engelsystem, pull requests merged in 2024-12, with the labels that each got.

#1450 Fix shifts apis missing schedule shifts
  src/Controllers/Api/ShiftsController.php
  tests/Unit/Controllers/Api/ShiftsControllerTest.php
Labels: Type: Bug(fix)

#1264 Signup advance hours for shift types
  db/factories/Shifts/ShiftTypeFactory.php
  db/migrations/2023_11_24_000000_add_signup_advance_hours_to_shift_types.php
  includes/model/Shifts_model.php
  includes/view/ShiftCalendarRenderer.php
  includes/view/ShiftCalendarShiftRenderer.php
  includes/view/Shifts_view.php
  resources/lang/de_DE/default.po
  resources/lang/en_US/default.po
  resources/views/admin/shifttypes/edit.twig
  resources/views/admin/shifttypes/view.twig
  src/Controllers/Admin/ShiftTypesController.php
  src/Models/Shifts/ShiftType.php
  tests/Unit/Controllers/Admin/ShiftTypesControllerTest.php
Labels: Type: Feature

#962 Implement voucher shortcut buttons
  includes/controller/users_controller.php
  includes/sys_page.php
  includes/view/User_view.php
  resources/assets/js/utils.js
  resources/assets/js/vendor.js
  resources/assets/js/voucher.js
  resources/lang/de_DE/default.po
  resources/views/layouts/app.twig
Labels: Type: Feature, Status: In Progress

#1492 fix goodie logs wording and to be filtered by user
  includes/pages/admin_active.php
  src/Controllers/Admin/UserGoodieController.php
Labels: Type: Bug(fix)
